version: '3.8'

services:
  rostov-ai-travel-client:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: rostov-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URL: mongodb://138.124.14.197:27017/rostov-ai-travel
      JWT_ACCESS_SECRET: your-super-secret-jwt-access-key-2024-CHANGE-ME
      JWT_REFRESH_SECRET: your-super-secret-jwt-refresh-key-2024-CHANGE-ME
      TWOGIS_API_KEY: 2aaa4ed7-7580-4e80-a139-f60e4be538c7
      OPENAI_API_KEY: ""
      CORS_ORIGIN: "*"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: rostov-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: rostov-ai-travel

volumes:
  mongo_data:
