version: '3.8'

services:
  rostov-ai-travel-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rostov-ai-travel-client
    ports:
      - "8081:8081"  # Expo web server
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Expo tunnel
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    networks:
      - rostov-ai-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  rostov-ai-network:
    driver: bridge
