version: '3.8'

services:

  rostov-ai-travel-client:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: rostov-client
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URL: mongodb://mongo:27017/rostov-ai-travel
      JWT_ACCESS_SECRET: your-super-secret-jwt-access-key-2024-CHANGE-ME-rostov-ai-travel
      JWT_REFRESH_SECRET: your-super-secret-jwt-refresh-key-2024-CHANGE-ME-rostov-ai-travel
      TWOGIS_API_KEY: 2aaa4ed7-7580-4e80-a139-f60e4be538c7
      OPENAI_API_KEY: ""
      OPENROUTER_API_KEY: "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"
      ROSREESTR_API_KEY: ""
      CORS_ORIGIN: "*"
      USE_EXPO_LOCATION: "true"
      USE_EXPO_MAPS: "true"
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - rostov-network

  mongo:
    image: mongo:7.0
    container_name: rostov-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: rostov-ai-travel
    networks:
      - rostov-network

volumes:
  mongo_data:

networks:
  rostov-network:
    driver: bridge
